### PR TITLE
add footer to all pages

### PR DESCRIPTION
**Pull request by Ogollah**
Title: add footer

*What does this PR do?*
Creates footer and modify buttons on all pages

*Description of the PR?*
It provides footers and change button colors for easy visibility to all the pages of the UI

*Screenshots*
add-footer-index
check
footer-home
footer-login
footer-profile
footer-reg-buz
footer-register

### CODE REVIEW

**Comment by ridgekimani** [comment]
screen shot 2018-02-28 at 4 51 23 pm
This is the title. So it shouldn't be on the description

**Comment by ridgekimani** [comment]
screen shot 2018-02-28 at 4 56 35 pm
Make the about text to be quite clear what it represents

**Comment by ridgekimani** [comment]
screen shot 2018-02-28 at 4 56 06 pm
Add even spacing between the text boxes

**Comment by ridgekimani** [comment]
Provide screenshots of your work

**Comment by ridgekimani** [comment]
Provide screenshots of your work
screen shot 2018-02-28 at 5 02 37 pm
One wouldn't know it's a button

**Comment by Ogollah** [comment]
@ridgekimani I have tried to make as many changes and upload screenshots

**Comment by ridgekimani** [comment]
With the description of the project in the readMe you can give a short description of what the project does instead of calling it `Andela challenge`

**Comment by WhitneyOgutu** [comment]
Feedback that @ridgekimani has given is sufficient. Otherwise, it looks good to me..

**Pull request merged**
